const tasks = [
    ["Plant a small tree or indoor plant 🌱"],
    ["Use your bicycle instead of a car 🚲"],
    ["Pick up litter in your area 🗑️"],
    ["Reuse an old container ♻️"],
    ["Take a shorter shower 💧"],
    ["Switch off unused lights 💡"],
    ["Donate old clothes 👕"],
    ["Try a vegetarian meal 🥗"],
    ["Avoid plastic bottles 🚫"],
    ["Collect rainwater 💦"],
    ["Recycle household waste ♻️"],
    ["Spend 10 mins in nature 🌳"],
    ["Educate a friend about recycling 🗣️"],
    ["Make compost from food waste 🍂"],
    ["Unplug devices not in use 🔌"],
    ["Use reusable bags 👜"],
    ["Read about climate change 📖"],
    ["Switch to LED bulbs 💡"],
    ["Take public transport 🚌"],
    ["Water plants early morning 🌼"],
    ["Avoid online fast delivery (reduce carbon) 📦"],
    ["Share your eco tip online 🌍"],
    ["Buy local produce 🥕"],
    ["Use less paper 📄"],
    ["Clean your neighborhood 🌇"],
    ["Avoid packaged snacks 🍫"],
    ["Spend a day screen-free 📵"],
    ["Switch to cold water laundry 🧺"],
    ["Teach someone about sustainability 🎓"],
    ["Reflect on your eco journey 🌎"],
];

export default tasks;
